name: CI

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env: 
      platform: aws
      region: us-east-1
      account: 222222222222

    steps:
      - name: Mostrar mensaje
        run: echo "Holas"

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.5

      - name: Install dependencies
        run: cd ./api && go mod tidy

      - name: Run tests
        run: cd ./api && go test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.22.5

      - name: Install AWS CLI
        run: sudo pip install awscli

      # Comenta o elimina el paso de depuración para evitar problemas de seguridad
      # - name: Debug AWS credentials
      #   run: echo "AWS Access Key ID=${{secrets.AWSKEY}} " && echo "AWS Secret Access Key= ${{secrets.AWSPASS}}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWSKEY }}
          aws-secret-access-key: ${{ secrets.AWSPASS }}
          aws-region: us-east-1

      - name: Build with SAM
        run: sam build --use-container

      - name: Deploy with SAM
        run: |
          sam deploy --stack-name multiply-app --region us-east-1 --no-fail-on-empty-changeset --no-confirm-changeset --save-params --capabilities CAPABILITY_IAM 

